require('config.colorscheme')
require('config.treesitter')
require('config.treesitter-playground')
require('config.file_explorer')
require('config.lualine')
require('config.autopairs')
require('config.saga')
require('config.comment')
require('config.colorizer')
-- require('config.cmp-npm')
-- require('config.cmp')
require("config.coq")
require('config.gitsigns')
require('config.indent_blankline')
require('config.neogit')
require('config.ts-autotag')
require('config.telescope')
require('config.git-worktree')
-- require('config.copilot')
-- require('config.shade')
